name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          tags: test-image:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: npm run validate && npm run build && npm run test:coverage
      - uses: codecov/codecov-action@v2
